

SELECT  distinct
    ORDER_ID,
	CUSTOMER_ID,
	ORDER_STATUS,
	ORDER_PURCHASE_TIMESTAMP,
	ORDER_APPROVED_AT,
	ORDER_DELIVERED_CARRIER_DATE,
	ORDER_DELIVERED_CUSTOMER_DATE,
	ORDER_ESTIMATED_DELIVERY_DATE , 
	CURRENT_TIMESTAMP AS created_at,
    CURRENT_TIMESTAMP AS updated_at ,
	CURRENT_TIMESTAMP AS load_date  
FROM SIGMATECH_DEMO.RAW_DATA.RAW_ORDERS 
