

SELECT  distinct
    CUSTOMER_ID ,
	CUSTOMER_UNIQUE_ID ,
	CUSTOMER_ZIP_CODE_PREFIX ,
	CUSTOMER_CITY,
	CUSTOMER_STATE , 
	CURRENT_TIMESTAMP AS created_at,
    CURRENT_TIMESTAMP AS updated_at ,
	CURRENT_TIMESTAMP AS load_date  
FROM SIGMATECH_DEMO.RAW_DATA.RAW_CUSTOMERS