


SELECT  distinct
    PRODUCT_ID ,
	PRODUCT_CATEGORY_NAME ,
	PRODUCT_NAME_LENGHT ,
	PRODUCT_DESCRIPTION_LENGHT,
	PRODUCT_PHOTOS_QTY ,
	PRODUCT_WEIGHT_G ,
	PRODUCT_LENGTH_CM ,
	PRODUCT_HEIGHT_CM,
	PRODUCT_WIDTH_CM ,
	CURRENT_TIMESTAMP AS created_at,
    CURRENT_TIMESTAMP AS updated_at ,
	CURRENT_TIMESTAMP AS load_date  
FROM SIGMATECH_DEMO.RAW_DATA.RAW_PRODUCTS 
