
SELECT  distinct
    CUSTOMER_ID ,
	CUSTOMER_UNIQUE_ID ,        
	CUSTOMER_ZIP_CODE_PREFIX ,
	CUSTOMER_CITY,
	CUSTOMER_STATE , 
	CURRENT_DATE as effective_date,
    NULL as expiry_date,
    TRUE as is_current 
FROM SIGMATECH_DEMO.PUBLIC.STG_CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL   