
SELECT  distinct
    o.ORDER_ID,
	o.CUSTOMER_ID,
	o.ORDER_PURCHASE_TIMESTAMP,
    oi.PRODUCT_ID,
    oi.PRICE ,
	oi.FREIGHT_VALUE,
    o.ORDER_STATUS
FROM SIGMATECH_DEMO.PUBLIC.STG_ORDERS o  
left join  SIGMATECH_DEMO.PUBLIC.RAW_ORDER_ITEMS oi  
on  o.ORDER_ID=oi.ORDER_ID
where 
    o.ORDER_ID IS NOT NULL AND 
	o.CUSTOMER_ID IS NOT NULL AND 
    oi.PRODUCT_ID  IS NOT NULL and 
    o.ORDER_STATUS IS NOT NULL